# Configuration spécifique pour GitHub Pages
# Ce fichier remplace certains paramètres de _config.yml pour le déploiement

# URL GitHub Pages
url: "https://nicolas-dabene.fr"  # Remplacez par votre nom d'utilisateur GitHub
baseurl: ""

# Environnement de production
environment: production

# Activer la génération des articles futurs pour permettre le partage en avance
# Les articles futurs sont générés mais pas listés sur la page blog (filtrés côté Liquid)
future: true
unpublished: false

# Optimisations pour la production
sass:
  style: compressed
  sourcemap: never

# Exclusions pour GitHub Pages
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - PLAN.md
  - scripts/
  - update-sitemap.sh
  - package.json
  - node_modules/
  - vendor/
  - .bundle/
  - .sass-cache/
  - .jekyll-cache/
  - gemfiles/