# Blog categories and subcategories structure - English version
# Format: category -> subcategories with icons and descriptions

artificial-intelligence:
  name: "Artificial Intelligence"
  icon: "fa-robot"
  description: "Generative AI for e-commerce, assisted development and AI agents"
  subcategories:
    - key: "ai-fundamentals"
      name: "AI Fundamentals"
      description: "Concepts, LLMs and cognitive architectures"
    - key: "assisted-development"
      name: "Assisted Development"
      description: "PDD, BMAD, Vibe Coding and Prompt Engineering"
    - key: "tools-platforms"
      name: "Tools & Platforms"
      description: "ChatGPT, Claude, Gemini, Mistral, DeepSeek"
    - key: "ai-ecommerce"
      name: "AI & E-commerce"
      description: "MCP PrestaShop, agents and automation"
    - key: "ai-strategy"
      name: "AI Strategy"
      description: "Trends, employment impact and adoption"
    - key: "ai-security"
      name: "AI Security"
      description: "Prompt leaks, personal data, compliance"

prestashop-ecommerce:
  name: "PrestaShop & E-commerce"
  icon: "fa-shopping-cart"
  description: "PrestaShop development, e-commerce strategies"
  subcategories:
    - key: "prestashop-fundamentals"
      name: "PrestaShop Fundamentals"
      description: "History, versions and architecture"
    - key: "prestashop-development"
      name: "PrestaShop Development"
      description: "Modules, hooks, API and best practices"
    - key: "prestashop-security"
      name: "PrestaShop Security"
      description: "Security standards and compliance"
    - key: "ecommerce-strategy"
      name: "E-commerce Strategy"
      description: "Black Friday, SEO, conversion"
    - key: "alternatives"
      name: "Alternatives"
      description: "Comparisons Shopify, Sylius, SaaS"

web-development:
  name: "Web Development"
  icon: "fa-code"
  description: "Languages and architectures powering AI-native e-commerce"
  subcategories:
    - key: "languages-frameworks"
      name: "Languages & Frameworks"
      description: "PHP, Symfony, JavaScript"
    - key: "architecture-design"
      name: "Architecture & Design"
      description: "Patterns, SOLID, Command Bus"
    - key: "quality-best-practices"
      name: "Quality & Best Practices"
      description: "Clean code, tests, documentation"
    - key: "api-integration"
      name: "API & Integration"
      description: "REST, API design, integrations"
    - key: "performance-optimization"
      name: "Performance & Optimization"
      description: "Web performance, caching, SEO"
    - key: "devops-deployment"
      name: "DevOps & Deployment"
      description: "GitHub Pages, hosting, automation"

automation:
  name: "Automation & Integration"
  icon: "fa-cogs"
  description: "MCP Protocol for e-commerce, AI workflows and intelligent automation"
  subcategories:
    - key: "mcp-protocol"
      name: "MCP Protocol"
      description: "Model Context Protocol and MCP servers"
    - key: "automation-tools"
      name: "Automation Tools"
      description: "n8n, Zapier, custom workflows"
    - key: "use-cases"
      name: "Use Cases"
      description: "Marketing automation, social media"

security:
  name: "Security & Cybersecurity"
  icon: "fa-shield-alt"
  description: "AI agent security, compliance and e-commerce protection"
  subcategories:
    - key: "threats-vulnerabilities"
      name: "Threats & Vulnerabilities"
      description: "Ransomware, data breaches, scams"
    - key: "compliance-regulation"
      name: "Compliance & Regulation"
      description: "GDPR, NIS2, CNIL, AI Act"
    - key: "security-best-practices"
      name: "Best Practices"
      description: "Validation, audit, controls"

strategy-market:
  name: "Strategy & Market"
  icon: "fa-chart-line"
  description: "Strategic vision, AI governance and e-commerce evolution"
  subcategories:
    - key: "business-strategy"
      name: "Business Strategy"
      description: "Business model, digital transformation"
    - key: "market-analysis"
      name: "Market Analysis"
      description: "Trends, geopolitics, competitiveness"
    - key: "career-skills"
      name: "Career & Skills"
      description: "Evolution, AI & employment, soft skills"
    - key: "industry-impact"
      name: "Industry Impact"
      description: "Future of work, autonomous agents"

seo-marketing:
  name: "SEO & Marketing"
  icon: "fa-search"
  description: "GEO, SEO and visibility in AI-powered search engines"
  subcategories:
    - key: "technical-seo"
      name: "Technical SEO"
      description: "E-commerce SEO, Google Shopping"
    - key: "seo-tools-strategies"
      name: "Tools & Strategies"
      description: "Google Ads, structured data"

tutorials:
  name: "Tutorials & Guides"
  icon: "fa-book"
  description: "Practical guides: MCP, PrestaShop and applied AI"
  subcategories:
    - key: "configuration"
      name: "Configuration"
      description: "Server setup, tools installation"
    - key: "practical-guides"
      name: "Practical Guides"
      description: "MCP, PrestaShop, dev step-by-step"
    - key: "troubleshooting"
      name: "Troubleshooting"
      description: "Debugging, problem solving"

retrospectives:
  name: "Retrospectives & Analysis"
  icon: "fa-calendar-alt"
  description: "Strategic reviews, retrospectives and in-depth analysis"
  subcategories:
    - key: "annual-retrospectives"
      name: "Annual Retrospectives"
      description: "Cybersecurity, events, trends reviews"
    - key: "in-depth-analysis"
      name: "In-Depth Analysis"
      description: "Comparative, market, strategic analysis"
