

- nom: "Devenez Acteur de l'IA - Chapitre 1 : L'Intelligence Artificielle pour Débutants"
  description: "Bienvenue dans ce voyage d'exploration au cœur de l'intelligence artificielle. Ce cours vous permettra de comprendre clairement ce qu'est l'IA, comment elle fonctionne et comment elle peut transformer votre quotidien, sans connaissances techniques préalables."
  image: "assets/images/produits/N0oPgOxKCqVIAQ6fh6TVT.png"
  lien_paiement: "https://ndabene.lemonsqueezy.com/buy/38fdbaf6-4c5b-406d-baef-52a11f230dc7"
  categorie: "Formation IA pour tous"
  prix: "9.99€ / HT"
  lemon_variant_id: 937957
  type: "ebook"
  format: "PDF"
  file_format: "pdf"

- nom: "Devenez Acteur de l'IA - Chapitre 2 : L'Impact Écologique et Sociétal de l'Intelligence Artificielle"
  description: "Une présentation sur les enjeux environnementaux et sociaux liés à l'utilisation croissante de l'IA dans notre société, et les solutions pour adopter une approche \"Green AI\"."
  image: "assets/images/produits/h1LhbYWAwPxLwadebXZxK.png"
  lien_paiement: "https://ndabene.lemonsqueezy.com/buy/175da6bb-e40b-411a-bf1b-f8264dfccbe4"
  categorie: "Formation IA pour tous"
  prix: "4.99€ / HT"
  lemon_variant_id: 937978
  type: "ebook"
  format: "PDF"
  file_format: "pdf"

- nom: "Devenez Acteur de l'IA - Chapitre 3 : L'Art du Prompt - Dialoguer avec l'IA"
  description: "Dans ce cours, vous découvrirez comment maîtriser l'art du prompt engineering pour communiquer efficacement avec n'importe quelle intelligence artificielle. À la fin de ce module, vous obtiendrez des résultats précis et exploitables en formulant des instructions claires et structurées."
  image: "assets/images/produits/FtoQOC9Ni6z2W8pBpbdnl.png"
  lien_paiement: ""
  categorie: "Formation IA pour tous"
  prix: "14.99€ / HT"
  lemon_variant_id: 
  type: "ebook"
  format: "PDF"
  file_format: "pdf"
