#!/bin/bash
set -e

# Validate XML artifacts generated by Jekyll

SITE_DIR="_site"
SITEMAP="$SITE_DIR/sitemap.xml"
FEED="$SITE_DIR/feed.xml"
FEED_EN="$SITE_DIR/feed_en.xml"

if ! command -v xmllint &> /dev/null; then
    echo "Error: xmllint is not installed. Please install libxml2-utils."
    exit 1
fi

echo "Starting XML validation..."

# Check sitemap
if [ -f "$SITEMAP" ]; then
    echo "✅ Validating $SITEMAP..."
    xmllint --noout "$SITEMAP"
else
    echo "⚠️  Warning: $SITEMAP not found."
fi

# Check feed
if [ -f "$FEED" ]; then
    echo "✅ Validating $FEED..."
    xmllint --noout "$FEED"
else
    echo "⚠️  Warning: $FEED not found."
fi

# Check feed_en if exists
if [ -f "$FEED_EN" ]; then
    echo "✅ Validating $FEED_EN..."
    xmllint --noout "$FEED_EN"
fi

echo "XML validation passed."
